### ISSUE TITLE
Cannot post request once a previous request is complete

### ISSUE THREAD

**Issue by fgypas** [elixir-europe/WES-ELIXIR#32] opened 2018-09-20 11:48 UTC
**Describe the bug**
Cannot post request once a previous request is complete.

**To Reproduce**
1. Post a request witht the following parameters:
_workflow_params_: { "input": {"class": "File", "path": "/absolute/path/to/WES-ELIXIR/cwl-tes/tests/resources/test.txt" }}
_workflow_type_: cwl
_workflow_type_version_: v1.0
_workflow_url_: /absolute/path/to/WES-ELIXIR/cwl-tes/tests/hashsplitter-workflow.cwl.yml

2. Wait for the pipeline to finish

3. Submit the same request. The new request is not triggered. 

**Expected behavior**
The new request should start.

**Screenshots**
![screen shot 2018-09-20 at 13 43 28](https://user-images.githubusercontent.com/6184370/45816210-39e57980-bcdb-11e8-9480-86ecfcf4017e.png)

**Software**
Add versions of relevant software, e.g.
 - OS: macOs Sierra 10.12.6
 - Browser: Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
Multiple workflows can be submitted before a request is COMPLETE.

**Comment by uniqueg** [comment] 2018-09-23 22:14
I can confirm this bug. However, this seems to be an issue with the Swagger library (or possibly connexion). If the parameters in the form fields are changed (even when changing and immediately changing back to the same values of the previous request), submission works fine. All other endpoints are unaffected by this as well.

We could think about using the original Swagger app and pointing it to the swagger.json generated by Connexion.

In any case, I will close the issue for now as it is neither critical, urgent or really in our hands.

**Closed** 2018-09-23 22:15 UTC
Labels: bug

**Comment by uniqueg** [comment] 2018-10-02 09:19
In fact it turned out to be an issue with Celery going bonkers, which also caused the app to lose track of workflow runs, leaving them in zombie mode (status "RUNNING") regardless of their actual state ("COMPLETE", "SYSTEM_ERROR" or "EXEUCTOR_ERROR"). Rolling back to Celery 4.1.1, as suggested in https://github.com/celery/celery/issues/4355#issuecomment-421706124, fixed both issues.
